// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootableSpawnHandle : RemoteTableHandle<EventContext, LootableSpawn>
        {
            protected override string RemoteTableName => "lootable_spawn";

            public sealed class SpawnIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(LootableSpawn row) => row.SpawnId;

                public SpawnIdUniqueIndex(LootableSpawnHandle table) : base(table) { }
            }

            public readonly SpawnIdUniqueIndex SpawnId;

            internal LootableSpawnHandle(DbConnection conn) : base(conn)
            {
                SpawnId = new(this);
            }

            protected override object GetPrimaryKey(LootableSpawn row) => row.SpawnId;
        }

        public readonly LootableSpawnHandle LootableSpawn;
    }
}
