// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootableItemTypeHandle : RemoteTableHandle<EventContext, LootableItemType>
        {
            protected override string RemoteTableName => "lootable_item_type";

            public sealed class TypeIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(LootableItemType row) => row.TypeId;

                public TypeIdUniqueIndex(LootableItemTypeHandle table) : base(table) { }
            }

            public readonly TypeIdUniqueIndex TypeId;

            internal LootableItemTypeHandle(DbConnection conn) : base(conn)
            {
                TypeId = new(this);
            }

            protected override object GetPrimaryKey(LootableItemType row) => row.TypeId;
        }

        public readonly LootableItemTypeHandle LootableItemType;
    }
}
