// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NavmeshConfigHandle : RemoteTableHandle<EventContext, NavMeshConfig>
        {
            protected override string RemoteTableName => "navmesh_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(NavMeshConfig row) => row.Id;

                public IdUniqueIndex(NavmeshConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NavmeshConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NavMeshConfig row) => row.Id;
        }

        public readonly NavmeshConfigHandle NavmeshConfig;
    }
}
