// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NavmeshGridHandle : RemoteTableHandle<EventContext, NavMeshGrid>
        {
            protected override string RemoteTableName => "navmesh_grid";

            public sealed class GridXIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(NavMeshGrid row) => row.GridX;

                public GridXIndex(NavmeshGridHandle table) : base(table) { }
            }

            public readonly GridXIndex GridX;

            public sealed class GridZIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(NavMeshGrid row) => row.GridZ;

                public GridZIndex(NavmeshGridHandle table) : base(table) { }
            }

            public readonly GridZIndex GridZ;

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(NavMeshGrid row) => row.Id;

                public IdUniqueIndex(NavmeshGridHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NavmeshGridHandle(DbConnection conn) : base(conn)
            {
                GridX = new(this);
                GridZ = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(NavMeshGrid row) => row.Id;
        }

        public readonly NavmeshGridHandle NavmeshGrid;
    }
}
