// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAddHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity);
        public event AdminAddHandler? OnAdminAdd;

        public void AdminAdd(SpacetimeDB.Identity identity)
        {
            conn.InternalCallReducer(new Reducer.AdminAdd(identity), this.SetCallReducerFlags.AdminAddFlags);
        }

        public bool InvokeAdminAdd(ReducerEventContext ctx, Reducer.AdminAdd args)
        {
            if (OnAdminAdd == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAdd(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAdd : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;

            public AdminAdd(SpacetimeDB.Identity Identity)
            {
                this.Identity = Identity;
            }

            public AdminAdd()
            {
            }

            string IReducerArgs.ReducerName => "admin_add";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminAddFlags;
        public void AdminAdd(CallReducerFlags flags) => AdminAddFlags = flags;
    }
}
