// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity);
        public event AdminRemoveHandler? OnAdminRemove;

        public void AdminRemove(SpacetimeDB.Identity identity)
        {
            conn.InternalCallReducer(new Reducer.AdminRemove(identity), this.SetCallReducerFlags.AdminRemoveFlags);
        }

        public bool InvokeAdminRemove(ReducerEventContext ctx, Reducer.AdminRemove args)
        {
            if (OnAdminRemove == null) return false;
            OnAdminRemove(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemove : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;

            public AdminRemove(SpacetimeDB.Identity Identity)
            {
                this.Identity = Identity;
            }

            public AdminRemove()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveFlags;
        public void AdminRemove(CallReducerFlags flags) => AdminRemoveFlags = flags;
    }
}
