// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BuildingPieceRemoveHandler(ReducerEventContext ctx, uint pieceId);
        public event BuildingPieceRemoveHandler? OnBuildingPieceRemove;

        public void BuildingPieceRemove(uint pieceId)
        {
            conn.InternalCallReducer(new Reducer.BuildingPieceRemove(pieceId), this.SetCallReducerFlags.BuildingPieceRemoveFlags);
        }

        public bool InvokeBuildingPieceRemove(ReducerEventContext ctx, Reducer.BuildingPieceRemove args)
        {
            if (OnBuildingPieceRemove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBuildingPieceRemove(
                ctx,
                args.PieceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BuildingPieceRemove : Reducer, IReducerArgs
        {
            [DataMember(Name = "piece_id")]
            public uint PieceId;

            public BuildingPieceRemove(uint PieceId)
            {
                this.PieceId = PieceId;
            }

            public BuildingPieceRemove()
            {
            }

            string IReducerArgs.ReducerName => "building_piece_remove";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags BuildingPieceRemoveFlags;
        public void BuildingPieceRemove(CallReducerFlags flags) => BuildingPieceRemoveFlags = flags;
    }
}
