// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BuildingPiecePlaceHandler(ReducerEventContext ctx, uint variantId, DbVector3 position, DbVector3 rotation);
        public event BuildingPiecePlaceHandler? OnBuildingPiecePlace;

        public void BuildingPiecePlace(uint variantId, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.BuildingPiecePlace(variantId, position, rotation), this.SetCallReducerFlags.BuildingPiecePlaceFlags);
        }

        public bool InvokeBuildingPiecePlace(ReducerEventContext ctx, Reducer.BuildingPiecePlace args)
        {
            if (OnBuildingPiecePlace == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBuildingPiecePlace(
                ctx,
                args.VariantId,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BuildingPiecePlace : Reducer, IReducerArgs
        {
            [DataMember(Name = "variant_id")]
            public uint VariantId;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public BuildingPiecePlace(
                uint VariantId,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.VariantId = VariantId;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public BuildingPiecePlace()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "building_piece_place";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags BuildingPiecePlaceFlags;
        public void BuildingPiecePlace(CallReducerFlags flags) => BuildingPiecePlaceFlags = flags;
    }
}
