// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreativeCameraSetEnabledHandler(ReducerEventContext ctx, bool enabled);
        public event CreativeCameraSetEnabledHandler? OnCreativeCameraSetEnabled;

        public void CreativeCameraSetEnabled(bool enabled)
        {
            conn.InternalCallReducer(new Reducer.CreativeCameraSetEnabled(enabled), this.SetCallReducerFlags.CreativeCameraSetEnabledFlags);
        }

        public bool InvokeCreativeCameraSetEnabled(ReducerEventContext ctx, Reducer.CreativeCameraSetEnabled args)
        {
            if (OnCreativeCameraSetEnabled == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreativeCameraSetEnabled(
                ctx,
                args.Enabled
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreativeCameraSetEnabled : Reducer, IReducerArgs
        {
            [DataMember(Name = "enabled")]
            public bool Enabled;

            public CreativeCameraSetEnabled(bool Enabled)
            {
                this.Enabled = Enabled;
            }

            public CreativeCameraSetEnabled()
            {
            }

            string IReducerArgs.ReducerName => "creative_camera_set_enabled";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreativeCameraSetEnabledFlags;
        public void CreativeCameraSetEnabled(CallReducerFlags flags) => CreativeCameraSetEnabledFlags = flags;
    }
}
