// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreativeCameraMoveHandler(ReducerEventContext ctx, DbVector3 position, DbVector3 rotation);
        public event CreativeCameraMoveHandler? OnCreativeCameraMove;

        public void CreativeCameraMove(DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.CreativeCameraMove(position, rotation), this.SetCallReducerFlags.CreativeCameraMoveFlags);
        }

        public bool InvokeCreativeCameraMove(ReducerEventContext ctx, Reducer.CreativeCameraMove args)
        {
            if (OnCreativeCameraMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreativeCameraMove(
                ctx,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreativeCameraMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public CreativeCameraMove(
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public CreativeCameraMove()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "creative_camera_move";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreativeCameraMoveFlags;
        public void CreativeCameraMove(CallReducerFlags flags) => CreativeCameraMoveFlags = flags;
    }
}
