// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EntityApplyDamageHandler(ReducerEventContext ctx, uint targetEntityId, float damage);
        public event EntityApplyDamageHandler? OnEntityApplyDamage;

        public void EntityApplyDamage(uint targetEntityId, float damage)
        {
            conn.InternalCallReducer(new Reducer.EntityApplyDamage(targetEntityId, damage), this.SetCallReducerFlags.EntityApplyDamageFlags);
        }

        public bool InvokeEntityApplyDamage(ReducerEventContext ctx, Reducer.EntityApplyDamage args)
        {
            if (OnEntityApplyDamage == null) return false;
            OnEntityApplyDamage(
                ctx,
                args.TargetEntityId,
                args.Damage
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EntityApplyDamage : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_entity_id")]
            public uint TargetEntityId;
            [DataMember(Name = "damage")]
            public float Damage;

            public EntityApplyDamage(
                uint TargetEntityId,
                float Damage
            )
            {
                this.TargetEntityId = TargetEntityId;
                this.Damage = Damage;
            }

            public EntityApplyDamage()
            {
            }

            string IReducerArgs.ReducerName => "entity_apply_damage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EntityApplyDamageFlags;
        public void EntityApplyDamage(CallReducerFlags flags) => EntityApplyDamageFlags = flags;
    }
}
