// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EntityResetHealthHandler(ReducerEventContext ctx, uint entityId);
        public event EntityResetHealthHandler? OnEntityResetHealth;

        public void EntityResetHealth(uint entityId)
        {
            conn.InternalCallReducer(new Reducer.EntityResetHealth(entityId), this.SetCallReducerFlags.EntityResetHealthFlags);
        }

        public bool InvokeEntityResetHealth(ReducerEventContext ctx, Reducer.EntityResetHealth args)
        {
            if (OnEntityResetHealth == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEntityResetHealth(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EntityResetHealth : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public uint EntityId;

            public EntityResetHealth(uint EntityId)
            {
                this.EntityId = EntityId;
            }

            public EntityResetHealth()
            {
            }

            string IReducerArgs.ReducerName => "entity_reset_health";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EntityResetHealthFlags;
        public void EntityResetHealth(CallReducerFlags flags) => EntityResetHealthFlags = flags;
    }
}
