// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InventoryCreateHandler(ReducerEventContext ctx);
        public event InventoryCreateHandler? OnInventoryCreate;

        public void InventoryCreate()
        {
            conn.InternalCallReducer(new Reducer.InventoryCreate(), this.SetCallReducerFlags.InventoryCreateFlags);
        }

        public bool InvokeInventoryCreate(ReducerEventContext ctx, Reducer.InventoryCreate args)
        {
            if (OnInventoryCreate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInventoryCreate(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InventoryCreate : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "inventory_create";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InventoryCreateFlags;
        public void InventoryCreate(CallReducerFlags flags) => InventoryCreateFlags = flags;
    }
}
