// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InventoryRemoveItemHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity, uint itemId, uint quantity);
        public event InventoryRemoveItemHandler? OnInventoryRemoveItem;

        public void InventoryRemoveItem(SpacetimeDB.Identity identity, uint itemId, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.InventoryRemoveItem(identity, itemId, quantity), this.SetCallReducerFlags.InventoryRemoveItemFlags);
        }

        public bool InvokeInventoryRemoveItem(ReducerEventContext ctx, Reducer.InventoryRemoveItem args)
        {
            if (OnInventoryRemoveItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInventoryRemoveItem(
                ctx,
                args.Identity,
                args.ItemId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InventoryRemoveItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;
            [DataMember(Name = "item_id")]
            public uint ItemId;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public InventoryRemoveItem(
                SpacetimeDB.Identity Identity,
                uint ItemId,
                uint Quantity
            )
            {
                this.Identity = Identity;
                this.ItemId = ItemId;
                this.Quantity = Quantity;
            }

            public InventoryRemoveItem()
            {
            }

            string IReducerArgs.ReducerName => "inventory_remove_item";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InventoryRemoveItemFlags;
        public void InventoryRemoveItem(CallReducerFlags flags) => InventoryRemoveItemFlags = flags;
    }
}
