// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootableDeleteSpawnHandler(ReducerEventContext ctx, uint spawnId);
        public event LootableDeleteSpawnHandler? OnLootableDeleteSpawn;

        public void LootableDeleteSpawn(uint spawnId)
        {
            conn.InternalCallReducer(new Reducer.LootableDeleteSpawn(spawnId), this.SetCallReducerFlags.LootableDeleteSpawnFlags);
        }

        public bool InvokeLootableDeleteSpawn(ReducerEventContext ctx, Reducer.LootableDeleteSpawn args)
        {
            if (OnLootableDeleteSpawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootableDeleteSpawn(
                ctx,
                args.SpawnId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootableDeleteSpawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "spawn_id")]
            public uint SpawnId;

            public LootableDeleteSpawn(uint SpawnId)
            {
                this.SpawnId = SpawnId;
            }

            public LootableDeleteSpawn()
            {
            }

            string IReducerArgs.ReducerName => "lootable_delete_spawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootableDeleteSpawnFlags;
        public void LootableDeleteSpawn(CallReducerFlags flags) => LootableDeleteSpawnFlags = flags;
    }
}
