// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootableDeleteAllSpawnsOfTypeHandler(ReducerEventContext ctx, uint typeId);
        public event LootableDeleteAllSpawnsOfTypeHandler? OnLootableDeleteAllSpawnsOfType;

        public void LootableDeleteAllSpawnsOfType(uint typeId)
        {
            conn.InternalCallReducer(new Reducer.LootableDeleteAllSpawnsOfType(typeId), this.SetCallReducerFlags.LootableDeleteAllSpawnsOfTypeFlags);
        }

        public bool InvokeLootableDeleteAllSpawnsOfType(ReducerEventContext ctx, Reducer.LootableDeleteAllSpawnsOfType args)
        {
            if (OnLootableDeleteAllSpawnsOfType == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootableDeleteAllSpawnsOfType(
                ctx,
                args.TypeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootableDeleteAllSpawnsOfType : Reducer, IReducerArgs
        {
            [DataMember(Name = "type_id")]
            public uint TypeId;

            public LootableDeleteAllSpawnsOfType(uint TypeId)
            {
                this.TypeId = TypeId;
            }

            public LootableDeleteAllSpawnsOfType()
            {
            }

            string IReducerArgs.ReducerName => "lootable_delete_all_spawns_of_type";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootableDeleteAllSpawnsOfTypeFlags;
        public void LootableDeleteAllSpawnsOfType(CallReducerFlags flags) => LootableDeleteAllSpawnsOfTypeFlags = flags;
    }
}
