// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootableCreateTypeHandler(ReducerEventContext ctx, uint typeId, string name, uint quantity, float respawnTimeSeconds, float lootDistance);
        public event LootableCreateTypeHandler? OnLootableCreateType;

        public void LootableCreateType(uint typeId, string name, uint quantity, float respawnTimeSeconds, float lootDistance)
        {
            conn.InternalCallReducer(new Reducer.LootableCreateType(typeId, name, quantity, respawnTimeSeconds, lootDistance), this.SetCallReducerFlags.LootableCreateTypeFlags);
        }

        public bool InvokeLootableCreateType(ReducerEventContext ctx, Reducer.LootableCreateType args)
        {
            if (OnLootableCreateType == null) return false;
            OnLootableCreateType(
                ctx,
                args.TypeId,
                args.Name,
                args.Quantity,
                args.RespawnTimeSeconds,
                args.LootDistance
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootableCreateType : Reducer, IReducerArgs
        {
            [DataMember(Name = "type_id")]
            public uint TypeId;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "quantity")]
            public uint Quantity;
            [DataMember(Name = "respawn_time_seconds")]
            public float RespawnTimeSeconds;
            [DataMember(Name = "loot_distance")]
            public float LootDistance;

            public LootableCreateType(
                uint TypeId,
                string Name,
                uint Quantity,
                float RespawnTimeSeconds,
                float LootDistance
            )
            {
                this.TypeId = TypeId;
                this.Name = Name;
                this.Quantity = Quantity;
                this.RespawnTimeSeconds = RespawnTimeSeconds;
                this.LootDistance = LootDistance;
            }

            public LootableCreateType()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "lootable_create_type";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootableCreateTypeFlags;
        public void LootableCreateType(CallReducerFlags flags) => LootableCreateTypeFlags = flags;
    }
}
