// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootableCheckRespawnsHandler(ReducerEventContext ctx);
        public event LootableCheckRespawnsHandler? OnLootableCheckRespawns;

        public void LootableCheckRespawns()
        {
            conn.InternalCallReducer(new Reducer.LootableCheckRespawns(), this.SetCallReducerFlags.LootableCheckRespawnsFlags);
        }

        public bool InvokeLootableCheckRespawns(ReducerEventContext ctx, Reducer.LootableCheckRespawns args)
        {
            if (OnLootableCheckRespawns == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootableCheckRespawns(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootableCheckRespawns : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "lootable_check_respawns";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootableCheckRespawnsFlags;
        public void LootableCheckRespawns(CallReducerFlags flags) => LootableCheckRespawnsFlags = flags;
    }
}
