// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootableCreateSpawnHandler(ReducerEventContext ctx, uint typeId, DbVector3 position, DbVector3 rotation);
        public event LootableCreateSpawnHandler? OnLootableCreateSpawn;

        public void LootableCreateSpawn(uint typeId, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.LootableCreateSpawn(typeId, position, rotation), this.SetCallReducerFlags.LootableCreateSpawnFlags);
        }

        public bool InvokeLootableCreateSpawn(ReducerEventContext ctx, Reducer.LootableCreateSpawn args)
        {
            if (OnLootableCreateSpawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootableCreateSpawn(
                ctx,
                args.TypeId,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootableCreateSpawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "type_id")]
            public uint TypeId;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public LootableCreateSpawn(
                uint TypeId,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.TypeId = TypeId;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public LootableCreateSpawn()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "lootable_create_spawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootableCreateSpawnFlags;
        public void LootableCreateSpawn(CallReducerFlags flags) => LootableCreateSpawnFlags = flags;
    }
}
