// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NavmeshUploadPointHandler(ReducerEventContext ctx, float x, float y, float z, int gridX, int gridZ);
        public event NavmeshUploadPointHandler? OnNavmeshUploadPoint;

        public void NavmeshUploadPoint(float x, float y, float z, int gridX, int gridZ)
        {
            conn.InternalCallReducer(new Reducer.NavmeshUploadPoint(x, y, z, gridX, gridZ), this.SetCallReducerFlags.NavmeshUploadPointFlags);
        }

        public bool InvokeNavmeshUploadPoint(ReducerEventContext ctx, Reducer.NavmeshUploadPoint args)
        {
            if (OnNavmeshUploadPoint == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNavmeshUploadPoint(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.GridX,
                args.GridZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NavmeshUploadPoint : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "grid_x")]
            public int GridX;
            [DataMember(Name = "grid_z")]
            public int GridZ;

            public NavmeshUploadPoint(
                float X,
                float Y,
                float Z,
                int GridX,
                int GridZ
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.GridX = GridX;
                this.GridZ = GridZ;
            }

            public NavmeshUploadPoint()
            {
            }

            string IReducerArgs.ReducerName => "navmesh_upload_point";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags NavmeshUploadPointFlags;
        public void NavmeshUploadPoint(CallReducerFlags flags) => NavmeshUploadPointFlags = flags;
    }
}
