// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NavmeshGetStatsHandler(ReducerEventContext ctx);
        public event NavmeshGetStatsHandler? OnNavmeshGetStats;

        public void NavmeshGetStats()
        {
            conn.InternalCallReducer(new Reducer.NavmeshGetStats(), this.SetCallReducerFlags.NavmeshGetStatsFlags);
        }

        public bool InvokeNavmeshGetStats(ReducerEventContext ctx, Reducer.NavmeshGetStats args)
        {
            if (OnNavmeshGetStats == null) return false;
            OnNavmeshGetStats(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NavmeshGetStats : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "navmesh_get_stats";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags NavmeshGetStatsFlags;
        public void NavmeshGetStats(CallReducerFlags flags) => NavmeshGetStatsFlags = flags;
    }
}
