// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NavmeshSetConfigHandler(ReducerEventContext ctx, float cellSize, float zTolerance, float boundsMinX, float boundsMinZ);
        public event NavmeshSetConfigHandler? OnNavmeshSetConfig;

        public void NavmeshSetConfig(float cellSize, float zTolerance, float boundsMinX, float boundsMinZ)
        {
            conn.InternalCallReducer(new Reducer.NavmeshSetConfig(cellSize, zTolerance, boundsMinX, boundsMinZ), this.SetCallReducerFlags.NavmeshSetConfigFlags);
        }

        public bool InvokeNavmeshSetConfig(ReducerEventContext ctx, Reducer.NavmeshSetConfig args)
        {
            if (OnNavmeshSetConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNavmeshSetConfig(
                ctx,
                args.CellSize,
                args.ZTolerance,
                args.BoundsMinX,
                args.BoundsMinZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NavmeshSetConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "cell_size")]
            public float CellSize;
            [DataMember(Name = "z_tolerance")]
            public float ZTolerance;
            [DataMember(Name = "bounds_min_x")]
            public float BoundsMinX;
            [DataMember(Name = "bounds_min_z")]
            public float BoundsMinZ;

            public NavmeshSetConfig(
                float CellSize,
                float ZTolerance,
                float BoundsMinX,
                float BoundsMinZ
            )
            {
                this.CellSize = CellSize;
                this.ZTolerance = ZTolerance;
                this.BoundsMinX = BoundsMinX;
                this.BoundsMinZ = BoundsMinZ;
            }

            public NavmeshSetConfig()
            {
            }

            string IReducerArgs.ReducerName => "navmesh_set_config";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags NavmeshSetConfigFlags;
        public void NavmeshSetConfig(CallReducerFlags flags) => NavmeshSetConfigFlags = flags;
    }
}
