// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NavmeshClearGridHandler(ReducerEventContext ctx);
        public event NavmeshClearGridHandler? OnNavmeshClearGrid;

        public void NavmeshClearGrid()
        {
            conn.InternalCallReducer(new Reducer.NavmeshClearGrid(), this.SetCallReducerFlags.NavmeshClearGridFlags);
        }

        public bool InvokeNavmeshClearGrid(ReducerEventContext ctx, Reducer.NavmeshClearGrid args)
        {
            if (OnNavmeshClearGrid == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNavmeshClearGrid(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NavmeshClearGrid : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "navmesh_clear_grid";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags NavmeshClearGridFlags;
        public void NavmeshClearGrid(CallReducerFlags flags) => NavmeshClearGridFlags = flags;
    }
}
