// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerConnectedHandler(ReducerEventContext ctx);
        public event PlayerConnectedHandler? OnPlayerConnected;

        public void PlayerConnected()
        {
            conn.InternalCallReducer(new Reducer.PlayerConnected(), this.SetCallReducerFlags.PlayerConnectedFlags);
        }

        public bool InvokePlayerConnected(ReducerEventContext ctx, Reducer.PlayerConnected args)
        {
            if (OnPlayerConnected == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerConnected(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerConnected : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "player_connected";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerConnectedFlags;
        public void PlayerConnected(CallReducerFlags flags) => PlayerConnectedFlags = flags;
    }
}
