// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerUpdateHandler(ReducerEventContext ctx, DbVector3 position, DbVector3 rotation, DbAnimationState animationState);
        public event PlayerUpdateHandler? OnPlayerUpdate;

        public void PlayerUpdate(DbVector3 position, DbVector3 rotation, DbAnimationState animationState)
        {
            conn.InternalCallReducer(new Reducer.PlayerUpdate(position, rotation, animationState), this.SetCallReducerFlags.PlayerUpdateFlags);
        }

        public bool InvokePlayerUpdate(ReducerEventContext ctx, Reducer.PlayerUpdate args)
        {
            if (OnPlayerUpdate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerUpdate(
                ctx,
                args.Position,
                args.Rotation,
                args.AnimationState
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerUpdate : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;
            [DataMember(Name = "animation_state")]
            public DbAnimationState AnimationState;

            public PlayerUpdate(
                DbVector3 Position,
                DbVector3 Rotation,
                DbAnimationState AnimationState
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
                this.AnimationState = AnimationState;
            }

            public PlayerUpdate()
            {
                this.Position = new();
                this.Rotation = new();
                this.AnimationState = new();
            }

            string IReducerArgs.ReducerName => "player_update";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerUpdateFlags;
        public void PlayerUpdate(CallReducerFlags flags) => PlayerUpdateFlags = flags;
    }
}
