// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerSetRotationHandler(ReducerEventContext ctx, DbVector3 rotation);
        public event PlayerSetRotationHandler? OnPlayerSetRotation;

        public void PlayerSetRotation(DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.PlayerSetRotation(rotation), this.SetCallReducerFlags.PlayerSetRotationFlags);
        }

        public bool InvokePlayerSetRotation(ReducerEventContext ctx, Reducer.PlayerSetRotation args)
        {
            if (OnPlayerSetRotation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerSetRotation(
                ctx,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerSetRotation : Reducer, IReducerArgs
        {
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public PlayerSetRotation(DbVector3 Rotation)
            {
                this.Rotation = Rotation;
            }

            public PlayerSetRotation()
            {
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "player_set_rotation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerSetRotationFlags;
        public void PlayerSetRotation(CallReducerFlags flags) => PlayerSetRotationFlags = flags;
    }
}
