// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerSetPositionHandler(ReducerEventContext ctx, DbVector3 position);
        public event PlayerSetPositionHandler? OnPlayerSetPosition;

        public void PlayerSetPosition(DbVector3 position)
        {
            conn.InternalCallReducer(new Reducer.PlayerSetPosition(position), this.SetCallReducerFlags.PlayerSetPositionFlags);
        }

        public bool InvokePlayerSetPosition(ReducerEventContext ctx, Reducer.PlayerSetPosition args)
        {
            if (OnPlayerSetPosition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerSetPosition(
                ctx,
                args.Position
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerSetPosition : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;

            public PlayerSetPosition(DbVector3 Position)
            {
                this.Position = Position;
            }

            public PlayerSetPosition()
            {
                this.Position = new();
            }

            string IReducerArgs.ReducerName => "player_set_position";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerSetPositionFlags;
        public void PlayerSetPosition(CallReducerFlags flags) => PlayerSetPositionFlags = flags;
    }
}
