// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;
        [DataMember(Name = "attack_range")]
        public float AttackRange;

        public Entity(
            uint EntityId,
            DbVector3 Position,
            DbVector3 Rotation,
            float Health,
            float MaxHealth,
            float AttackRange
        )
        {
            this.EntityId = EntityId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.AttackRange = AttackRange;
        }

        public Entity()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
