// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LootableItemType
    {
        [DataMember(Name = "type_id")]
        public uint TypeId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "quantity")]
        public uint Quantity;
        [DataMember(Name = "respawn_time_us")]
        public long RespawnTimeUs;
        [DataMember(Name = "loot_distance")]
        public float LootDistance;

        public LootableItemType(
            uint TypeId,
            string Name,
            uint Quantity,
            long RespawnTimeUs,
            float LootDistance
        )
        {
            this.TypeId = TypeId;
            this.Name = Name;
            this.Quantity = Quantity;
            this.RespawnTimeUs = RespawnTimeUs;
            this.LootDistance = LootDistance;
        }

        public LootableItemType()
        {
            this.Name = "";
        }
    }
}
