// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LootableSpawn
    {
        [DataMember(Name = "spawn_id")]
        public uint SpawnId;
        [DataMember(Name = "type_id")]
        public uint TypeId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;
        [DataMember(Name = "is_looted")]
        public bool IsLooted;
        [DataMember(Name = "looted_at_us")]
        public long LootedAtUs;

        public LootableSpawn(
            uint SpawnId,
            uint TypeId,
            DbVector3 Position,
            DbVector3 Rotation,
            bool IsLooted,
            long LootedAtUs
        )
        {
            this.SpawnId = SpawnId;
            this.TypeId = TypeId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.IsLooted = IsLooted;
            this.LootedAtUs = LootedAtUs;
        }

        public LootableSpawn()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
