// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NavMeshConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "cell_size")]
        public float CellSize;
        [DataMember(Name = "z_tolerance")]
        public float ZTolerance;
        [DataMember(Name = "bounds_min_x")]
        public float BoundsMinX;
        [DataMember(Name = "bounds_min_z")]
        public float BoundsMinZ;

        public NavMeshConfig(
            uint Id,
            float CellSize,
            float ZTolerance,
            float BoundsMinX,
            float BoundsMinZ
        )
        {
            this.Id = Id;
            this.CellSize = CellSize;
            this.ZTolerance = ZTolerance;
            this.BoundsMinX = BoundsMinX;
            this.BoundsMinZ = BoundsMinZ;
        }

        public NavMeshConfig()
        {
        }
    }
}
