// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NavMeshGrid
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "z")]
        public float Z;
        [DataMember(Name = "grid_x")]
        public int GridX;
        [DataMember(Name = "grid_z")]
        public int GridZ;

        public NavMeshGrid(
            uint Id,
            float X,
            float Y,
            float Z,
            int GridX,
            int GridZ
        )
        {
            this.Id = Id;
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.GridX = GridX;
            this.GridZ = GridZ;
        }

        public NavMeshGrid()
        {
        }
    }
}
