// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "look_direction")]
        public DbVector2 LookDirection;
        [DataMember(Name = "animation_state")]
        public DbAnimationState AnimationState;
        [DataMember(Name = "last_valid_position")]
        public DbVector3 LastValidPosition;
        [DataMember(Name = "last_update_timestamp")]
        public long LastUpdateTimestamp;
        [DataMember(Name = "movement_speed")]
        public float MovementSpeed;
        [DataMember(Name = "interaction_range")]
        public float InteractionRange;
        [DataMember(Name = "reconciliation_safety_margin")]
        public float ReconciliationSafetyMargin;

        public Player(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            uint EntityId,
            bool Online,
            DbVector2 LookDirection,
            DbAnimationState AnimationState,
            DbVector3 LastValidPosition,
            long LastUpdateTimestamp,
            float MovementSpeed,
            float InteractionRange,
            float ReconciliationSafetyMargin
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.EntityId = EntityId;
            this.Online = Online;
            this.LookDirection = LookDirection;
            this.AnimationState = AnimationState;
            this.LastValidPosition = LastValidPosition;
            this.LastUpdateTimestamp = LastUpdateTimestamp;
            this.MovementSpeed = MovementSpeed;
            this.InteractionRange = InteractionRange;
            this.ReconciliationSafetyMargin = ReconciliationSafetyMargin;
        }

        public Player()
        {
            this.LookDirection = new();
            this.AnimationState = new();
            this.LastValidPosition = new();
        }
    }
}
